name: Package Application with Pyinstaller

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    permissions:
        contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        requirements: .github/workflows/requirements.txt

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Windows Build (Pyinstaller)"
        files: |
          dist/windows/qumupam.exe
